// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2-gormc

package handler

import (
	"net/http"

	nocache "gorm-zero-example/services/api/internal/handler/nocache"
	"gorm-zero-example/services/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users/id/:id",
				Handler: queryUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/add",
				Handler: addUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/update",
				Handler: updateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/del",
				Handler: delUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users/id/:id",
				Handler: nocache.NocacheQueryUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/add",
				Handler: nocache.NocacheAddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/update",
				Handler: nocache.NocacheUpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/del",
				Handler: nocache.NocacheDelUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/nocache"),
	)
}
