// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gorm-zero-example/services/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: queryUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/add",
				Handler: addUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/update",
				Handler: updateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: delUserHandler(serverCtx),
			},
		},
	)
}
