// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGormzeroUnameIdPrefix = "cache:gormzero:uname:id:"
)

type (
	unameModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Uname) error

		FindOne(ctx context.Context, id int64) (*Uname, error)
		Update(ctx context.Context, tx *gorm.DB, data *Uname) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultUnameModel struct {
		gormc.CachedConn
		table string
	}

	Uname struct {
		Id       int64  `gorm:"column:id"`
		Username string `gorm:"column:username"`
	}
)

func (Uname) TableName() string {
	return "`uname`"
}

func newUnameModel(conn *gorm.DB, c cache.CacheConf) *defaultUnameModel {
	return &defaultUnameModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`uname`",
	}
}

func (m *defaultUnameModel) Insert(ctx context.Context, tx *gorm.DB, data *Uname) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUnameModel) FindOne(ctx context.Context, id int64) (*Uname, error) {
	gormzeroUnameIdKey := fmt.Sprintf("%s%v", cacheGormzeroUnameIdPrefix, id)
	var resp Uname
	err := m.QueryCtx(ctx, &resp, gormzeroUnameIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Uname{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUnameModel) Update(ctx context.Context, tx *gorm.DB, data *Uname) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultUnameModel) getCacheKeys(data *Uname) []string {
	if data == nil {
		return []string{}
	}
	gormzeroUnameIdKey := fmt.Sprintf("%s%v", cacheGormzeroUnameIdPrefix, data.Id)
	cacheKeys := []string{
		gormzeroUnameIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultUnameModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Uname{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUnameModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultUnameModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGormzeroUnameIdPrefix, primary)
}

func (m *defaultUnameModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Uname{}).Where("`id` = ?", primary).Take(v).Error
}

func (m *defaultUnameModel) tableName() string {
	return m.table
}
